### ISSUE TITLE
error when building some models

### ISSUE THREAD

**Issue by andersonda** [ecu-pase-lab/mysql-query-construction-analysis#5]
example: running `model = buildModelForNumberedCall(7,5);` results in `NoSuchField("header")`

**Comment by mahills** [comment]
Do you have a line number on this? There were some changes in the serialized information, so you may have to rebuild some/all of it, depending on what changed (I would just rebuild the binaries for the systems in the corpus, then re-extract all the other info as well, although I'm guessing this is a cached control flow graph so that may be the place to start).

**Comment by andersonda** [comment]
Thanks, this fixed it.
